version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: node-auth-db
    environment:
      MYSQL_DATABASE: "node-auth"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
